### ISSUE TITLE
on handling power events

### ISSUE THREAD

**Issue by selvanair** [xkjyeah/openvpnserv2#6]
The only reason openvpn is affected by suspend/resume is because the tun/tap driver shuts down during that time. Latest versions of openvpn handles this internally and should come back up on resume. The service has no way of knowing that and second guessing what to do on power events is not a clean approach.

So I suggest to remove the stop/restart on suspend/resume. Even without that the service already acts as a watchdog and restarts openvpn.exe if it dies for any reason. That should take care of all eventualities.

**Comment by xkjyeah** [comment]
0f65f4ec2f6cf961846245ee298c9a05fedc33ca
